<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DEANMID" failures="4" tests="19" name="runner.TestRunner" time="76.844" errors="0" timestamp="2022-12-26T08:57:28 EET" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="4.567"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.493">
    <failure message="expected [https://demo.nopcommerce.com/new-online-store-is-open] but found [https://demo.nopcommerce.com/news/rss/1]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/new-online-store-is-open] but found [https://demo.nopcommerce.com/news/rss/1]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.SD07_FollowUsTest.confirmNewTab(SD07_FollowUsTest.java:36)
at ✽."https://demo.nopcommerce.com/new-online-store-is-open" is opened in new tab(file:///C:/Users/dell/Desktop/3abd%20el%208afoor%20el%20bor3y/demonopcommerce/src/main/resources/Features/F07_FollowUs.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="7.534"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.999"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.065"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.121"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.321"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.551"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.016"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.172">
    <failure message="The following asserts failed:
	expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at stepDefinitions.SD06_HomeSliderTest.userIsBeNavigatedToTheSecondProductSuccessfully(SD06_HomeSliderTest.java:37)
at ✽.user is be navigated to the second product successfully(file:///C:/Users/dell/Desktop/3abd%20el%208afoor%20el%20bor3y/demonopcommerce/src/main/resources/Features/F06_HomeSliders.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.927"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.391"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="6.835"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.119"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.633">
    <failure message="The following asserts failed:
	expected [true] but found [false],
	expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at stepDefinitions.SD04_SearchTest.userShouldFindTheInSearchResult(SD04_SearchTest.java:39)
at ✽.user should find the "book" in search result(file:///C:/Users/dell/Desktop/3abd%20el%208afoor%20el%20bor3y/demonopcommerce/src/main/resources/Features/F04_Search.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.584">
    <failure message="The following asserts failed:
	expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at stepDefinitions.SD06_HomeSliderTest.userIsBeNavigatedToTheFirstProductSuccessfully(SD06_HomeSliderTest.java:23)
at ✽.user is be navigated to the first product successfully(file:///C:/Users/dell/Desktop/3abd%20el%208afoor%20el%20bor3y/demonopcommerce/src/main/resources/Features/F06_HomeSliders.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.616"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.062"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.838"/>
  <system-out/>
</testsuite> <!-- runner.TestRunner -->
